import type { NextPage } from "next";
import ethers from "ethers";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import { useIsMounted } from "../hooks/useIsMounted";
import { useAccount } from "wagmi";

function getContract() {
  
}
const Home: NextPage = () => {
  const mounted = useIsMounted();
  const { address } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <NavBar />

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Stable Coin</h1>
        {/* {mounted ? address : null} */}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
